# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  engine_config = debug
  test_config = debug

else ifeq ($(config),release)
  engine_config = release
  test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := engine test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

engine:
ifneq (,$(engine_config))
	@echo "==== Building engine ($(engine_config)) ===="
	@${MAKE} --no-print-directory -C . -f engine.make config=$(engine_config)
endif

test: engine
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make config=$(test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f engine.make clean
	@${MAKE} --no-print-directory -C . -f test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   engine"
	@echo "   test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"